# Importing libraries

In [3]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings("ignore")
print("all libraries imported successfully...")

all libraries imported successfully...

In [7]:
RawData = pd.read_csv(r"C:\Users\Rishik Reddy\OneDrive\Desktop\IPL_Stats\RawDataset\matches.csv")
RawData.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [11]:
RawData.shape
print("the no of rows:",RawData.shape[0])
print("the no of columns:",RawData.shape[1])

the no of rows: 1095
the no of columns: 20

In [13]:
RawData.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [8]:
RawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [9]:
RawData.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

## Checking NUll values

In [14]:
RawData.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [18]:
# Now filling the numeric type columns with mean or median
RawData['result_margin']=RawData['result_margin'].fillna(RawData['result_margin'].median())
RawData['target_runs']=RawData['target_runs'].fillna(RawData['target_runs'].mean())
RawData['target_overs']=RawData['target_overs'].fillna(RawData['target_overs'].mean())

# Now filling Object type columns with mode
RawData['city']=RawData['city'].fillna(RawData['city'].mode()[0])
RawData['player_of_match']=RawData['player_of_match'].fillna(RawData['player_of_match'].mode()[0])
RawData['winner']=RawData['winner'].fillna(RawData['winner'].mode()[0]) 
RawData['method'] = RawData['method'].fillna('Normal')

In [19]:
RawData.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

## Checking for duplicates values

In [21]:
RawData.duplicated().sum()

if RawData.duplicated().sum()==0:
    print("No duplicate values found in the dataset.")
else:
    print("Duplicate values found in the dataset. Removing duplicates...")
    RawData.drop_duplicates(inplace=True)

No duplicate values found in the dataset.

## Converting

In [25]:
RawData['date'] = pd.to_datetime(RawData['date'], errors='coerce')
RawData['season'] = RawData['date'].dt.year

In [26]:
RawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   int32
 2   city             1095 non-null   object
 3   date             1095 non-null   datetime64[ns]
 4   match_type       1095 non-null   object
 5   player_of_match  1095 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1095 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1095 non-null   float64
 14  target_runs      1095 non-null   float64
 15  target_overs     1095 non-null   float64
 16  super_over       1095 non-null   object
 17  method           1095 non-null   object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: datetime64[ns](1), float64(3), int32(1), int64(1), object(14)
memory usage: 166.9+ KB

## chaning Data type of Super_over column

In [27]:
RawData['super_over'] = RawData['super_over'].map({
    'Y': 1,
    'N': 0
}).astype(int)

In [29]:
RawData['super_over'].dtype
RawData['super_over'].head()

0    0
1    0
2    0
3    0
4    0
Name: super_over, dtype: int64

## Team Insights

In [22]:
RawData.nunique()

id                 1095
season               17
city                 36
date                823
match_type            8
player_of_match     291
venue                58
team1                19
team2                19
toss_winner          19
toss_decision         2
winner               19
result                4
result_margin        98
target_runs         171
target_overs         16
super_over            2
method                1
umpire1              62
umpire2              62
dtype: int64

### **Most Match Wins**

In [33]:
RawData['winner'].value_counts().head(5)

winner
Mumbai Indians                 149
Chennai Super Kings            138
Kolkata Knight Riders          131
Royal Challengers Bangalore    116
Rajasthan Royals               112
Name: count, dtype: int64

### **Toss Winner Analysis**

In [34]:
RawData['toss_winner'].value_counts().head(10)

toss_winner
Mumbai Indians                 143
Kolkata Knight Riders          122
Chennai Super Kings            122
Rajasthan Royals               120
Royal Challengers Bangalore    113
Sunrisers Hyderabad             88
Kings XI Punjab                 85
Delhi Daredevils                80
Delhi Capitals                  50
Deccan Chargers                 43
Name: count, dtype: int64

### **Team Winning Percentage**

In [38]:
win_prec = (RawData['winner'].value_counts() / len(RawData)) * 100
print(win_prec.head(10).round(2))

winner
Mumbai Indians                 13.61
Chennai Super Kings            12.60
Kolkata Knight Riders          11.96
Royal Challengers Bangalore    10.59
Rajasthan Royals               10.23
Sunrisers Hyderabad             8.04
Kings XI Punjab                 8.04
Delhi Daredevils                6.12
Delhi Capitals                  4.38
Deccan Chargers                 2.65
Name: count, dtype: float64

## Player Insights

### **Most Player of the Match Awards**

In [39]:
RawData['player_of_match'].value_counts().head(10)

player_of_match
AB de Villiers    30
CH Gayle          22
RG Sharma         19
V Kohli           18
DA Warner         18
MS Dhoni          17
YK Pathan         16
RA Jadeja         16
SR Watson         16
AD Russell        15
Name: count, dtype: int64

## Match Insights

### **Matches Played Per Season**

In [ ]:
# For Final
final_matches = RawData[RawData['match_type'] == 'Final']
final_teams = pd.concat([final_matches['team1'], final_matches['team2']])
final_team_counts = final_teams.value_counts()
print("Teams with most Final appearances:")
print(final_team_counts.head(5))

# For Qualifier 1
qual1_matches = RawData[RawData['match_type'] == 'Qualifier 1']
qual1_teams = pd.concat([qual1_matches['team1'], qual1_matches['team2']])
qual1_team_counts = qual1_teams.value_counts()
print("\nTeams with most Qualifier 1 appearances:")
print(qual1_team_counts.head(5))

# For Qualifier 2
qual2_matches = RawData[RawData['match_type'] == 'Qualifier 2']
qual2_teams = pd.concat([qual2_matches['team1'], qual2_matches['team2']])
qual2_team_counts = qual2_teams.value_counts()
print("\nTeams with most Qualifier 2 appearances:")
print(qual2_team_counts.head(5))

Teams with most Final appearances:
Chennai Super Kings            10
Mumbai Indians                  6
Kolkata Knight Riders           4
Royal Challengers Bangalore     3
Sunrisers Hyderabad             3
Name: count, dtype: int64

Teams with most Qualifier 1 appearances:
Chennai Super Kings            7
Mumbai Indians                 5
Kolkata Knight Riders          3
Royal Challengers Bangalore    2
Gujarat Titans                 2
Name: count, dtype: int64

Teams with most Qualifier 2 appearances:
Mumbai Indians                 4
Sunrisers Hyderabad            4
Chennai Super Kings            4
Kolkata Knight Riders          3
Royal Challengers Bangalore    3
Name: count, dtype: int64

### **Biggest Win Margins**

In [ ]:
top_margins = RawData['result_margin'].value_counts().head(10).index

for margin in top_margins:

    teams_for_margin = RawData[RawData['result_margin'] == margin]['winner'].value_counts().head(5)

    print(f"\nMargin {margin}: {teams_for_margin.to_dict()}")

Margin 6.0: {'Kings XI Punjab': 19, 'Mumbai Indians': 15, 'Kolkata Knight Riders': 15, 'Chennai Super Kings': 14, 'Rajasthan Royals': 11}

Margin 7.0: {'Kolkata Knight Riders': 18, 'Rajasthan Royals': 15, 'Chennai Super Kings': 14, 'Royal Challengers Bangalore': 13, 'Kings XI Punjab': 12}

Margin 5.0: {'Mumbai Indians': 21, 'Chennai Super Kings': 15, 'Kolkata Knight Riders': 14, 'Sunrisers Hyderabad': 11, 'Rajasthan Royals': 10}

Margin 8.0: {'Mumbai Indians': 19, 'Kolkata Knight Riders': 15, 'Royal Challengers Bangalore': 13, 'Rajasthan Royals': 11, 'Kings XI Punjab': 10}

Margin 4.0: {'Mumbai Indians': 10, 'Chennai Super Kings': 8, 'Rajasthan Royals': 8, 'Kings XI Punjab': 7, 'Royal Challengers Bangalore': 7}

Margin 9.0: {'Mumbai Indians': 10, 'Royal Challengers Bangalore': 8, 'Delhi Daredevils': 7, 'Sunrisers Hyderabad': 7, 'Kolkata Knight Riders': 6}

Margin 3.0: {'Rajasthan Royals': 12, 'Kolkata Knight Riders': 5, 'Royal Challengers Bangalore': 4, 'Chennai Super Kings': 3, 'Gujarat Titans': 3}

Margin 10.0: {'Royal Challengers Bangalore': 7, 'Kolkata Knight Riders': 4, 'Rajasthan Royals': 4, 'Delhi Daredevils': 3, 'Deccan Chargers': 3}

Margin 2.0: {'Rajasthan Royals': 4, 'Chennai Super Kings': 4, 'Royal Challengers Bangalore': 3, 'Kolkata Knight Riders': 3, 'Kings XI Punjab': 1}

Margin 1.0: {'Mumbai Indians': 3, 'Royal Challengers Bangalore': 3, 'Kings XI Punjab': 2, 'Kolkata Knight Riders': 2, 'Chennai Super Kings': 2}

In [49]:
RawData.to_csv('../CleanDataset/cleaned_matches.csv', index=False)
print("Dataset saved successfully....")

Dataset saved successfully....